dist: precise # https://github.com/travis-ci/travis-ci/issues/8331
language: python
python:
 - "2.7"
 - "3.6"
install:
 - pip install -e .
 - pip install pymysql psycopg2
 - pip install coverage coveralls
script: coverage run setup.py test
after_success:
 - coveralls
services:
 - postgres
 - mysql
