name: commcare-export release actions
on:
  release:
    types: [published]

jobs:
  generate_windows_exe:
    name: Generate Windows exe as release asset
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pyinstaller
        shell: pwsh
        run: python -m pip install pyinstaller

      - name: Generate exe
        shell: pwsh
        run: |
          pip install commcare-export
          pip install -r build_exe/requirements.txt
          pyinstaller --dist ./dist/windows commcare-export.spec

      - name: Upload release assets
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "./dist/windows/*"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
